#+TITLE: Факторы прямого воздействия
#+AUTHOR: Вася Панков
#+EXPORT_FILE_NAME: Text
#+latex_header: \usepackage[utf8x]{inputenc}
#+latex_header: \usepackage[T2A]{fontenc}
#+latex_header: \usepackage[russian,english]{babel}

* Внешняя среда организации

Перед тем как поговорить о факторах прямого воздействиях необходимо поговорить вообще
о внешней среде.

Внешняя среда - это совокупность материальных и нематериальных явлений,
находящихся вне организации, но влияющих на ее деятельность.

Общие характеристики внешней среды:

- все факторы находятся во взаимосвязи;
- сложность среды (число факторов, на которые организация обязана реагировать,
  уровень вариативности каждого фактора);
- подвижность (скорость, с которой происходит изменение внешней среды);
- неопределенность внешней среды (ограничения информации и достоверность этой информации,
  подвижность среды усугубляет сложность неопределенности).

Сама же внешняя среда может быть прямого и косвенного воздействия.

* 5 Элементов прямого воздействия

** Поставщики
Поставщики это те, кто обеспечивают организацию сырьем,
комплектующими, оборудованием, запчастями.
Поставщики поддерживают движение предприятия «на входе».
Выбором оптимальных схем, путей и объемов поставок занимается логистика.

** Потребители
Потребители это те, кто использует производимую организацией продукцию и услуги.
Потребители фактически обеспечивают смысл деятельности организации.
Именно для удовлетворения запросов потребителей создается и функционирует
предприятие. Поэтому потребитель является центральной фигурой внешней
среды каждой организации. Изучением своих потребителей, их запросы,
пожелания к потребляемой продукции и услугам занимается маркетинг.
В сферу маркетинга входит не только изучение, но и поиск,
и даже «создание» новых потребителей.

** Ресурсы
Ресурсы это потенциальные силы и средства,
которые могут быть вовлечены в производственный процесс.
Основными видами ресурсов производства являются: трудовые, финансовые,
энергетические.

** Конкуренты
Конкуренты это фирмы, предлагающие аналогичную продукции и услуги.
Основной конкурентный показатель любой продукции - это соотношение
«цена-качество».

** Правовые условия

Правовые условия - это трудовое и налоговое законодательство страны.
Законы должны предоставлять равные условия предприятиям всех форм собственности.
Налоговая система обязана стимулировать производство.


* Итог
Внешняя среда является единственным потребителем и оценщиком результатов деятельности
организации.
Выживание организации определяется тем, примет ли внешняя среда или отторгнет
ее продукцию (услуги), сколько она заплатит за воспринятую продукцию,
и какую долю товарного рынка среда предоставит организации.
